# Flask settings
FLASK_DEBUG = False
FLASK_HOST = '0.0.0.0'
FLASK_PORT = '5000'

# Flask-Restplus settings
RESTPLUS_SWAGGER_UI_DOC_EXPANSION = 'list'
RESTPLUS_VALIDATE = True
RESTPLUS_MASK_SWAGGER = False
RESTPLUS_ERROR_404_HELP = False
